---
name: "test build"

on:
  pull_request:
  push:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble build -y
