---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble build -y
      - run: Compress-Archive -Path release/*.exe -DestinationPath utils-win64.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: >
            utils-win64.zip
            release/parasite.dll

